# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 383918d39e771062dd044b6535cdd16a5149689b80a7dc2395e0a750599c7c4135802e90c538efc141768d7bc8d3dc7ac911078ce98e88a7e585ddff727c422c

test:
  secret_key_base: db537d70ac5037c30e05e0a2d173e2e80fb4323742e3568d5595a3b3ab3c9e636de1dc072583d4b262e291e90ebd273bea1e4eed7dcb496cd676e00524ef2e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
